name: Deploy Environments via rsync

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env_name: [staging]
    environment:
      name: ${{ matrix.env_name }}
      url: ${{ vars.WEBSITE_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
      - name: Filter only `.md` files with directory structure
        run: |
          mkdir filtered
          find . -name '*.md' -exec bash -c '
            for f; do
              mkdir -p "filtered/$(dirname "$f")"
              cp "$f" "filtered/$f"
            done
          ' bash {} +

      - name: Upload filtered `.md` files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "filtered/"
          rm: true
          target: "${{ secrets.DEV_PATH }}"

      - name: Clean up key file
        run: rm -f key.pem
